@startjson
{
  "name": "CISInfo",
  "description": "Schema for the CIS info object",
  "fields": [
    {
      "name": "cisinfo",
      "type": "object",
      "required": true,
      "fields": [
        {
          "name": "cis",
          "type": "string",
          "description": "Уникальный идентификатор товара (CIS)."
        },
        {
          "name": "packageType",
          "type": "string",
          "enum": [
            {"value": "UNIT", "description": "Товарная упаковка"},
            {"value": "LEVEL1", "description": "Транспортная упаковка 1-го уровня"},
            {"value": "LEVEL2", "description": "Транспортная упаковка 2-го уровня (SSCC)"},
            {"value": "LEVEL3", "description": "Упаковка 3-го уровня"},
            {"value": "LEVEL4", "description": "Упаковка 4-го уровня"},
            {"value": "LEVEL5", "description": "Упаковка 5-го уровня"},
            {"value": "BUNDLE", "description": "Комплект"},
            {"value": "АТК", "description": "Агрегированный таможенный код"}
          ]
        },
        {
          "name": "status",
          "type": "string",
          "enum": [
            {"value": "EMITTED", "description": "Эмитирован"},
            {"value": "APPLIED", "description": "Нанесён"},
            {"value": "INTRODUCED", "description": "Введен в оборот"},
            {"value": "WRITTEN_OFF", "description": "Утилизирован"},
            {"value": "WITHDRAWN", "description": "Выведен из оборота"},
            {"value": "INTRODUCED_RETURNED", "description": "Возвращён в оборот"},
            {"value": "DISAGGREGATED", "description": "Дезагрегирован"},
            {"value": "APPLIED_NOT_PAID", "description": "Нанесён, не оплачен"}
          ]
        },
        {
          "name": "parent",
          "type": "string",
          "description": 
            "CIS родительского товара, если данный товар находится в составе другого товара."
        },
        {
          "name": "child",
          "type": "array",
          "$itemsType":"string",
          "$itemsDescription":"Массив CIS дочерних товаров."
        },
        {
          "name":"emissionType",
          "type":"string",
          "$description":"Тип эмиссии: LOCAL, FOREIGN, REMAINS, CROSSBORDER."
        },
        {
          "$name":"emissionDate",
          "$type":"string",
          "$format":"date-time",
          "$description":"Дата эмиссии товара в формате yyyy-MM-ddTHH:mm:ss.SSS'Z'."
        },
        {
          "$name":"productionDate",
          "$type":"string",
          "$format":"date-time",
          "$description":"Дата производства в формате yyyy-MM-ddTHH:mm:ss.SSS'Z'."
        },
        {
          "$name":"expirationDate",
          "$type":"string",
          "$format":"date-time",
          "$description":"Дата истечения срока годности в формате yyyy-MM-ddTHH:mm:ss.SSS'Z'."
        },
        {
          "$name":"producer",
          "$type":"object",
          "$fields":[
            {
              "$name":"producerInn",
              "$type":"string",
              "$description":"ИНН производителя товара."
            },
            {
              "$name":"producerName",
              "$type":"string",
              "$description":"Наименование производителя товара."
            }
          ],
          "$description":"Информация о производителе товара."
        },
        {
          "$name":"owner",
          "$type":"object",
          "$fields":[
            {
              "$name":"ownerInn",
              "$type":"string",
              "$description":"ИНН текущего владельца товара."
            },
            {
              "$name":"ownerName",
              "$type":"string",
              "$description":"Наименование текущего владельца товара."
            }
          ],
           "$description":"Информация о текущем владельце товара."
        }
      ],
      "$required":["cis","packageType","status","owner"],
      "$additionalProperties" : false
    }
  ]
}
@endjson
