@startuml
title "UML Sequence diagrams about BNPL (777)"
    actor Потребитель
    participant Продавец
    participant ФинансоваяОрганизация

    Потребитель->Продавец: Запрос на покупку с BNPL
    Продавец->ФинансоваяОрганизация: Запрос на одобрение BNPL
    ФинансоваяОрганизация-->Продавец: Одобрение/отказ
    Продавец->Потребитель: Уведомление о статусе

    alt Успех
        Потребитель->Продавец: Подтверждение покупки
        Продавец->ФинансоваяОрганизация: Информация о транзакции
        ФинансоваяОрганизация->Потребитель: Уведомление о платежах
        Потребитель->ФинансоваяОрганизация: Платежи по BNPL
    else Отказ
        Продавец->Потребитель: Уведомление об отказ
    end
    
@enduml
