@startuml
page 1x2
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

'!pragma layout smetana /'сначала простой элемент, затем вложенный элемент.'/
left to right direction

!$class_type = "(T,#00a86b)"
!$next = ".."

  package Name_1 <<Frame>> { 
    class Clearing <1> <<$code взаимозачеты>> {
      .. определение ..
      [[https://spaceneobank.atlassian.net/wiki/spaces/PSE/overview {Клиринг это - безналичные расчёты между странами, компаниями, предприятиями и банками за поставленные, проданные друг другу товары, ценные бумаги и оказанные услуги, осуществляемые путём взаимного зачёта, исходя из условий баланса платежей.} Payme Clearing System]]
      [[https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B8%D1%80%D0%B8%D0%BD%D0%B3 {Кли́ринг англ. clearing — очистка безналичные расчёты между государствами, странами, компаниями, предприятиями, банками и так далее, за поставленные, проданные друг другу товары, ценные бумаги и оказанные услуги, осуществляемые путём взаимного зачёта, исходя из условий баланса платежей.} Подробнее на wiki]]
      [[https://habr.com/ru/companies/oleg-bunin/articles/695262/ {коммент 2} как реализован клиринг Мир]]
      .. методы ..
    }
    class PreScoring <№> <<$class_type название>> {
      .. определение ..
       
      .. методы ..
      
    }
    class Scoring <№> <<$class_type название>> {
      .. определение ..
       для разных продуктов - разные скоринговые модели
      .. методы ..

    }
    
    Scoring -- Wings
    
    class Wings <№> <<$class_type название>> {
      .. определение ..
       
      .. методы ..
      
    }
    class Processing <№>  <<$class_type название>> {
      .. определение ..
         [[https://spaceneobank.atlassian.net/wiki/x/PwDIs {Процессинг - сущность которая дает возможность работать с внешними процессингами (Uzcard, Humo). У него есть 3 основные (которые делятся) и несколько мелких задач: \n 1. Получение информация о карте \n 2. Выполнение разных действий по карте \n 3. Работа с транзакциями по карте \n 4. Другое} Процессинг]]
      
      .. методы ..
      
    }
    class Identify <№> <<$class_type название>> {
      .. определение ..
       
      .. методы ..
      
    }
    class Veryfication <№> <<$class_type название>> {
      .. определение ..
       
      .. методы ..
      
    }
    class Billing <№> <<$class_type название>>  {
      .. определение ..
      [[https://spaceneobank.atlassian.net/wiki/spaces/PLTP/pages/3024028199/Payme {Биллинг - это централизованная система для работ с подписками и периодическими услугами (т.к. мониторинг платежей, уведомления штрафов ГАИ и тд.), в котором реализована плавающая дата списания, что позволяет плавно распределить нагрузку. Последующие даты списания настраиваются конфигурациями в самой услуге, каждая из которых может быть настроена по своему, требования этих конфигураций будет выполнять биллинг (К примеру: в услуге можно настроить период биллинга, по истечении которого будут списываться средства за продление, длительность периода демо-версии, а так же в течении какого периода будут производиться попытки списания).} Биллинг Сервисов Payme]]
      .. методы ..
      
    }
  }
  
  /'-----------------------------------------------------------------------'/
  
  package Name_2 <<Frame>> {
     class IABS <№> <<$class_type название>> {
      .. определение ..
       $code IABS is АБС
      .. методы ..
      
    }
     class ICL <№> <<$class_type название>> {
      .. определение ..
       
      .. методы ..
      
    }
     class Collection <№> <<$class_type название>> {
      .. определение ..
       
      .. методы ..
      
    }
     class ? <№> <<$class_type попадает в 1С>> {
      .. определение ..
       
      .. методы ..
      
    }
  }
  
  /'-----------------------------------------------------------------------'/
   package BNPL <<Frame>> {
    class BNPL_online <№> <<$class_type название>>  {
      1. [[https://spaceneobank.atlassian.net/jira/plans/211/scenarios/211/timeline?vid=910 {} Development board in Jira ]]
      2. [[https://spaceneobank.atlassian.net/wiki/spaces/PLTP/pages/3128328244/Payme+-+BNPL+AKA+Otsrochka+-+DelayP {} Documentation for BNPL online]]
      3. [[https://spaceneobank.atlassian.net/wiki/x/gwEHtQ {} Documentation for product]]
      4. [[https://miro.com/app/board/uXjVKNszEq8=/ {} Miro board about product]]
      5. [[https://miro.com/app/board/uXjVNWUeg0U=/ {} Miro board second]]
      6. [[https://miro.com/app/board/uXjVLda9LjA=/ {} BPMN diagram ]]
    }
  }

@enduml
